--- #YAML:1.0
name:                Bot-BasicBot-Pluggable-Module-TwitterFriendsStatus
version:             0.1
abstract:            Echo Twitter comments
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.36
distribution_type:   module
requires:     
    Bot::BasicBot::Pluggable::Module: 0
    LWP::UserAgent:                0
    XML::Simple:                   0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Gryphon Shafer <gryphon@cpan.org>
